# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/firewatch.jpg'

# Special
background='#150a19'
foreground='#f5e5cc'
cursor='#f5e5cc'

# Colors
color0='#150a19'
color1='#E16F33'
color2='#A7554C'
color3='#F58B33'
color4='#FEA533'
color5='#F0A362'
color6='#FFD7A5'
color7='#f5e5cc'
color8='#aba08e'
color9='#E16F33'
color10='#A7554C'
color11='#F58B33'
color12='#FEA533'
color13='#F0A362'
color14='#FFD7A5'
color15='#f5e5cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
