# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/firewatch_alt.png'

# Special
background='#170001'
foreground='#f6da89'
cursor='#f6da89'

# Colors
color0='#170001'
color1='#AA4C1A'
color2='#D86E1B'
color3='#F08A1B'
color4='#FFB01B'
color5='#E49B22'
color6='#FFC31B'
color7='#f6da89'
color8='#ac985f'
color9='#AA4C1A'
color10='#D86E1B'
color11='#F08A1B'
color12='#FFB01B'
color13='#E49B22'
color14='#FFC31B'
color15='#f6da89'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
