# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/warframe.png'

# Special
background='#0b0b0c'
foreground='#bfbebd'
cursor='#bfbebd'

# Colors
color0='#0b0b0c'
color1='#6B6154'
color2='#71706D'
color3='#887863'
color4='#7F807F'
color5='#9C8B72'
color6='#D1AF72'
color7='#bfbebd'
color8='#858584'
color9='#6B6154'
color10='#71706D'
color11='#887863'
color12='#7F807F'
color13='#9C8B72'
color14='#D1AF72'
color15='#bfbebd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
